# coding: utf-8

"""
    ICOS

    Access to ICOS data and metadata. ICOS is a pan european Research Infrastructure measuring and observing greenhouse gases.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: info@icos-cp.eu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_icoscp_get_collections(self):
        """Test case for icoscp_get_collections

        collections  # noqa: E501
        """
        pass

    def test_icoscp_get_data(self):
        """Test case for icoscp_get_data

        data  # noqa: E501
        """
        pass

    def test_icoscp_get_provisional_stations(self):
        """Test case for icoscp_get_provisional_stations

        provisional  # noqa: E501
        """
        pass

    def test_icoscp_get_stations(self):
        """Test case for icoscp_get_stations

        stations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
