# coding: utf-8

# flake8: noqa
"""
    ICOS

    Access to data and metadata from the european Integrated Carbon Observation System, ICOS. The Carbon Poral is a one stop shop for european high quality greenhouse gas measurements.  This API is for users who like to have an easy access to the most common data objects and information about the research stations.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: info@icos-cp.eu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
